'use client'

import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainSidebar from "./components/main-sidebar";
import { useProjectsStore } from "../stores/serviceStore";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const setServices = useProjectsStore((s) => s.setProjects)

  useEffect(() => {
    const fetchServices = async () => {
      const res = await fetch("http://localhost:3004/projects")
      const json = await res.json() 
      console.log(json)
      setServices(json)
    }

    fetchServices()
  }, [setServices])

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-screen flex flex-row text-sidebar-foreground">
          <MainSidebar />
          <div className="flex-1 border-t border-l border-border mt-4 rounded-tl-xl overflow-y-auto bg-background-secondary text-foreground p-10">
            <div className="p-6 space-y-8">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
